[project]
name = "mars-rec-sys"
version = "0.1.0"
description = "API for course recommendation system"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "fastapi>=0.139.2",
    "pyjwt>=2.8.0",
    "python-multipart>=0.0.32",
    "torch==2.6.0+cu124",
    "torchvision==0.21.0+cu124",
    "uvicorn[standard]>=0.51.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu124"

[[tool.uv.index]]
url = "https://pypi.org/simple"

[dependency-groups]
dev = [
]
