"""add recommendation_logs indexes (no-op)

Autogenerated against a database whose ``alembic_version`` had been stamped at
``c31f53b0d12f`` by ``core.database.init_db``, so Alembic could not see that the
three ``ix_rec_logs_*`` indexes already existed. They are created twice already:

* in the initial revision ``c31f53b0d12f``, and
* by ``core.database.init_db`` via ``CREATE INDEX IF NOT EXISTS``.

Re-creating them here raised ``sqlite3.OperationalError: index
ix_rec_logs_timestamp already exists`` during ``alembic upgrade head``, which
aborts container startup because ``scripts/docker-entrypoint.sh`` runs under
``set -eu``. The revision is kept (rather than deleted) so the migration chain
stays stable for databases already stamped at this version, but both directions
are intentionally no-ops.

Revision ID: a0882f19c5b2
Revises: c31f53b0d12f
Create Date: 2026-07-26 16:39:53.655315

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a0882f19c5b2"
down_revision: str | Sequence[str] | None = "c31f53b0d12f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """No-op: ix_rec_logs_* already exist from c31f53b0d12f."""


def downgrade() -> None:
    """No-op: the indexes belong to c31f53b0d12f, which owns dropping them."""
